FROM eclipse-temurin:17-jdk-alpine
ADD target/Authentication-Service-0.0.1-SNAPSHOT.jar Authentication-Service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/Authentication-Service-0.0.1-SNAPSHOT.jar"]