spring:
  application:
    name: Administrative-Service
  data:
    mongodb:
      uri: 
      auto-index-creation: true

server:
  port: 8086

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/