server:
  port: 8081

spring:
  application:
    name: API-Gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: Course-Management-Service
          uri: lb://Course-Management-Service
          predicates:
            - Path=/api/v1/courses/**
          filters:
            - AuthenticationFilter

        - id: LearnerService
          uri: lb://LearnerService
          predicates:
            - Path=/api/LearnerService/**
          filters:
            - AuthenticationFilter

        - id: Administrative-Service
          uri: lb://Administrative-Service
          predicates:
            - Path=/admin/**
          filters:
            - AuthenticationFilter

        - id: notificationServicespring
          uri: lb://notificationServicespring
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthenticationFilter

        - id: Payment-Service
          uri: lb://Payment-Service
          predicates:
            - Path=/payment/**
          filters:
            - AuthenticationFilter

        - id: Authentication-Service
          uri: lb://Authentication-Service
          predicates:
            - Path=/api/v1/auth/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT

eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# Trace everything with Zipkin
management:
  tracing:
    sampling:
      probability: 1.0