eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: notificationServicespring
  data:
    mongodb:
      uri: 
      auto-index-creation: true
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 8087